// Generated by CoffeeScript 1.6.2
/* File: src/coffee/angularjs/demo-app/app.coffee
*/


/* File: src/coffee/angularjs/demo-app/helpers/*.coffee
*/


/* File: src/coffee/angularjs/demo-app/services/*.coffee
*/


/* File: src/coffee/angularjs/demo-app/controllers/*.coffee
*/


(function() {


}).call(this);
